name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

jobs:
  ping-function:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Function
        run: |
          curl -X POST https://sjsjagoqzjvgsiyejial.supabase.co/functions/v1/send-email \
          -H "Authorization: Bearer sb_publishable_fbfUw36cqPdExnkaHxxtBw_Kfx9Sj5L" \
          -H "Content-Type: application/json" \
          -d '{"replyTo":"keepalive@example.com","subject":"keep-alive","message":"ping"}'
